environment:
  vix:
    threshold: 30.0
    volume: 0.4

targets:
  - name: SQQQ
    holding_weight: 60
    strategies:
      - name: strategy_test_2
        priority: 2
        params:
          sigma_level: [1.83, 3.72, 7.5 ]
          volume: 0.10
          max_short_ratio: 0.30

      - name: strategy_test
        priority: 1
        params:
          sigma_level: [1.83, 3.72, 7.5 ]
          volume: 0.10
          max_short_ratio: 0.30

  - name: SOXS
    holding_weight: 40
    strategies:
      - name: strategy_test
        priority: 1
        params:
          sigma_level: [3.18, 6.51, 13.2]
          volume: 0.10
          max_short_ratio: 0.30

  - name: SPXU
    holding_weight: 100
    strategies:
      - name: strategy_test
        priority: 1
        params:
          sigma_level: [3.18, 6.51, 13.2]
          volume: 0.10
          max_short_ratio: 0.30